# catppuccin colorscheme
base="#1e1e2e"
text="#cdd6f4"
green="#a6e3a1"
blue="#89b4fa"
rosewater="#f5e0dc"
flamingo="#f2cdcd"
pink="#f5c2e7"
mauve="#cda6f7"
red="#f38ba8"
maroon="#eba0ac"
peach="#fab387"
yellow="#f9e2af"
teal="#94e2d5"
sky="#89dceb"
sapphire="#74c7ec"
lavender="#b4befe"
subtext1="#bac2de"
subtext0="#a6adc8"
overlay2="#9399b2"
overlay1="#7f849c"
overlay0="#6c7086"
surface2="#586b70"
surface1="#45475a"
surface0="#313244"
mantle="#181825"
crust="#11111b"

# color mapping
bg="${green}"
default_fg="${text}" 
session_fg="${base}"
session_selection_fg="${session_fg}"
session_selection_bg="${bg}"
active_window_fg="${bg}"
active_pane_border="${lavender}"

session_style="#[fg=${session_fg},bold,bg=${bg}]"
section_style="#[fg=${text}, bg=${surface1}]"
section_prefix_style="#[fg=${surface2},bg=default]"
session_prefix_style="#[fg=${bg},bg=${surface1}]"

path_name="#(echo #{pane_current_path} | sed 's|$HOME|~|')"

set -g status-justify left 
set -g status-left-length 200   # default: 10
set -g status-right-length 200  # default: 10
set -g status-left "${session_style}   ${session_prefix_style}${section_style} #S ${section_prefix_style}"
set -g status-right "${section_prefix_style}${section_style} ${path_name} ${session_prefix_style}${session_style} #(whoami) "
set -g status-style "bg=${mantle}"

set -g window-status-format "#[fg=${text},bg=default] #I:#W "
set -g window-status-current-format "#[fg=${active_window_fg},bg=default]  #I:#W "
set -g window-status-last-style "fg=${default_fg},bg=default"
set -g window-status-separator ""

set -g message-command-style "bg=default,fg=${default_fg}"
set -g message-style "bg=default,fg=${default_fg}"

set -g mode-style "bg=${session_selection_bg},fg=${session_selection_fg}"

set -g pane-active-border-style "fg=${active_pane_border},bg=default"
set -g pane-border-style "fg=brightblack,bg=default"
