# Enable 256-color and true-color (24-bit) support in tmux
set -g default-terminal "screen-256color" # Set terminal type for 256-color support
set -ga terminal-overrides ",*256col*:Tc" # Override to enable true-color for compatible terminals

# General
set -g set-clipboard on            # Use system clipboard
set -g mouse on                    # Enable mouse support
set -g status-interval 3           # Update the status bar every 3 seconds (default: 15)
set -g detach-on-destroy off       # Don't exit from tmux when closing a session

# Set prefix key
unbind C-b                   # Unbind the default prefix key
set -g prefix C-Space        # Set new prefix key to Ctrl+Space

# Refresh tmux config with r
unbind r
bind r source-file ~/.config/tmux/tmux.conf

# Split horizontally in CWD with \
unbind %
bind \\ split-window -h -c "#{pane_current_path}"

# Split vertically in CWD with -
unbind \" 
bind - split-window -v -c "#{pane_current_path}"

# New window in the same path
bind c new-window -c "#{pane_current_path}"

# Use vim arrow keys to resize
bind -r j resize-pane -D 5
bind -r k resize-pane -U 5
bind -r l resize-pane -R 5
bind -r h resize-pane -L 5
bind -r m resize-pane -Z   # Use m key to maximize pane

# Enable vi mode to allow vim movements
set-window-option -g mode-keys vi

# Start selecting text with "v"
# Enter copy mode: prefix + [
bind-key -T copy-mode-vi 'v' send -X begin-selection

# Copy text with "y"
bind -T copy-mode-vi 'y' send-keys -X copy-pipe-and-cancel "pbcopy"

# Don't exit copy mode when dragging  with mouse
unbind -T copy-mode-vi MouseDragEnd1Pane

# Start windows and panes at 1 instead of 0
set -g base-index 1
set -g pane-base-index 1
set -g renumber-windows on # Automatically renumber windows when one is closed

# List of plugins
set -g @plugin 'tmux-plugins/tpm'

set -g @plugin 'christoomey/vim-tmux-navigator' # Enable navigating between nvim and tmux
# set -g @plugin 'tmux-plugins/tmux-continuum'    # Automatically saves sessions every 15 minutes  

# Persist tmux sessions after computer restart
# Save session: prefix + Ctrl-c
# Resurrect session: prefix + Ctrl-r
# set -g @plugin 'tmux-plugins/tmux-resurrect'    

# Configure status bar
# Custom theme
source-file ~/.config/tmux/catppuccin.conf

# set -g @resurrect-capture-pane-contents 'on'
# set -g @continuum-restore 'on'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
